######################################################################
# Automatically generated by qmake (1.04a) Sat Feb 22 17:31:07 2003
######################################################################

QT       += core gui

greaterThan(QT_MAJOR_VERSION, 4): QT += widgets


TEMPLATE = app
INCLUDEPATH += ../../libqutexr/
LIBS += ../../libqutexr.so

#Input
HEADERS += clientimpl.h ui_client.h
FORMS   += client.ui
SOURCES += clientimpl.cpp main.cpp
