# File generated by kdevelop's qmake manager.
# -------------------------------------------
# Subdirectory relative to the main directory of the project: ./wposbo
# Destination is an application: wposbo

QT += gui network xml sql dbus
greaterThan(QT_MAJOR_VERSION, 4): QT += widgets webenginewidgets

QMAKE_CXXFLAGS += -std=c++20

INSTALLS += etc \
            icons \
            target

target.path = /usr/bin

icons.files += icons/*
icons.path = /usr/share/ntpv_backoffice
icons.extra = ./postinst

etc.files += etc/*
etc.path = /etc/ntpv_backoffice

TARGETDEPS += ../wposwidget/libwposwidget.so \
              ../wposcore/libwposcore.so \
              ../libbslxml/libbslxml.so

LIBS += -lwposwidget \
        -lwposcore \
        -lbslxml \
        -lgdc \
        -lgd \
        -lxml2 \
        -ljpeg \
        -lpng \
        -lz \
        -lm

INCLUDEPATH +=  . \
                .. \
               ../..\
               /wposwidget \
               /wposcore \
               /libbslxml \
               /usr/include/gdchart \
               /usr/include/libxml2 \
               /usr/include/libxml2/libxml \
               /usr/include/c++/9

MOC_DIR = .moc
UI_DIR = .ui
OBJECTS_DIR = .obj

QMAKE_LIBDIR = ../wposwidget \
               ../wposcore \
               ../libbslxml

DEFINES = HAVE_LIBFREETYPE
TARGET = wposbo

#CONFIG += release warn_on qt thread
CONFIG += debug warn_on qt thread
TEMPLATE = app

DBUS_ADAPTORS     += com.wiresens.databasemodule.xml \
                     com.wiresens.optioncreationwidget.xml \
                     com.wiresens.optionupdatewidget.xml \
                     com.wiresens.optiondeletionwidget.xml \
                     com.wiresens.nprofitreportwidget.xml \
                     com.wiresens.memstickwidget.xml \
                     com.wiresens.fx2000configwidget.xml \
                     com.wiresens.productoptionmodule.xml \
                     com.wiresens.productoffermodule.xml \
                     com.wiresens.productmodule.xml \
                     com.wiresens.usermodule.xml

DBUS_HEADER_FILES += databasemodule/databasemodule.h \
                     menusystem/offers_options/optionupdatewidget.h \
                     menusystem/offers_options/optioncreationwidget.h \
                     menusystem/offers_options/optiondeletionwidget.h \
                     menusystem/reports/nprofitreportwidget.h \
                     menusystem/system/memstickwidget.h \
                     menusystem/system/fx2000configwidget.h \
                     productsmodule/optionsmodule/productoptionmodule.h \
                     productsmodule/offersmodule/productoffermodule.h \
                     productsmodule/productmodule.h \
                     usersmodule/usermodule.h

#Qt D-BUS qdbuscpp2xml compiler flags.
#export all public slot
DBUS_FLAGS = -M

#export scriptable signals
DBUS_FLAGS += -s

#output option
DBUS_OUT_FLAGS = -o

# Newer versions of QtCreator do builds in a separate directory. As a
# result, we need to append the source directory to DBUS files.
#
for(file, DBUS_HEADER_FILES) {
  DBUS_PWD_FILES += $$PWD/$${file}
}

qdbuscpp2xml.name = qdbuscpp2xml ${QMAKE_FILE_IN}
qdbuscpp2xml.input = DBUS_PWD_FILES
qdbuscpp2xml.output = com.wiresens.${QMAKE_FILE_BASE}.xml
qdbuscpp2xml.commands = qdbuscpp2xml $$DBUS_FLAGS ${QMAKE_FILE_IN} $$DBUS_OUT_FLAGS com.wiresens.${QMAKE_FILE_BASE}.xml
qdbuscpp2xml.CONFIG = no_link
qdbuscpp2xml.depends = $$DBUS_HEADER_FILES
qdbuscpp2xml.clean = com.wiresens.${QMAKE_FILE_BASE}.xml
QMAKE_EXTRA_COMPILERS += qdbuscpp2xml

HEADERS += database/productsmoduledb.h \
           database/usersmoduledb.h \
           database/productoptionsmoduledb.h \
           database/productoffersmoduledb.h \
           database/historicdb.h \
           databasemodule/databasemoduleinterface.h \
           databasemodule/databasemodule.h \
    mainscreen.h \
    menusystem/database/databaseconfigwidget.h \
    menusystem/design/addinvitationscreenwidget.h \
    menusystem/design/deleteinvitationscreenwidget.h \
    menusystem/design/deleteofferwidget.h \
    menusystem/design/invitationscreendesignwidget.h \
    menusystem/design/posdesignselectorwidget.h \
    menusystem/design/productscreendesignwidget.h \
    menusystem/design/submenuinfoframe.h \
    menusystem/menus/genericscreenwidget.h \
    menusystem/menus/instantiator.h \
    menusystem/menus/mainscreenwidget.h \
           menusystem/utils.h \
           menusystem/design/shortcutbuttonwidget.h \
           menusystem/design/nticketdesignwidget.h \
           menusystem/products/productinsertionwidget.h \
           menusystem/products/advancedproductinsertionwidget.h \
           menusystem/products/advancedproducteditionwidget.h \
           menusystem/products/advancedproductdeletionwidget.h \
           menusystem/products/advancedproductupdatewidget.h \
           menusystem/products/productxmfileupdatewidget.h \
           menusystem/products/productoffercreationwidget.h \
           menusystem/products/productoptioncreationwidget.h \
           menusystem/products/basicproductcreationwidget.h \
           menusystem/products/basicproductupdatewidget.h \
           menusystem/products/basicproducteditionwidget.h \
           menusystem/offers_options/offereditionwidget.h \
           menusystem/offers_options/offercreationwidget.h \
           menusystem/offers_options/offerupdatewidget.h \
           menusystem/offers_options/offerdeletionwidget.h \
           menusystem/offers_options/optioneditionwidget.h \
           menusystem/offers_options/optioncreationwidget.h \
           menusystem/offers_options/optionupdatewidget.h \
           menusystem/offers_options/optiondeletionwidget.h \
           productsmodule/optionsmodule/productoptionmoduleinterface.h \
           productsmodule/optionsmodule/productoptionmodule.h \
           productsmodule/productmoduleinterface.h \
           productsmodule/offersmodule/productoffermoduleinterface.h \
           productsmodule/offersmodule/productoffermodule.h \
           productsmodule/productmodule.h \
           usersmodule/usermodule.h \
           menusystem/menus/supportwidget.h \
           menusystem/menus/techwidget.h \
           menusystem/reports/perszwidget.h \
           menusystem/reports/persticketwidget.h \
           menusystem/reports/nprofitreportwidget.h \
           menusystem/reports/reportinterface.h \
#           menusystem/reports/nprodandofferreportwidget.h \
#           menusystem/system/fx2000configwidget.h \
#           menusystem/system/memstickwidget.h \
           menusystem/system/fx2000enrollwidget.h \
           menusystem/system/memstickinterface.h \
           menusystem/system/devicesconfigwidget.h \
           menusystem/users/usereditionwidget.h \
           menusystem/users/usercreatewidget.h \
           menusystem/users/userupdatewidget.h \
           menusystem/users/userselectwidget.h \
    usersmodule/usermoduleinterface.h

SOURCES += database/productoffersmoduledb.cpp \
           database/productsmoduledb.cpp \
           database/usersmoduledb.cpp \
           database/productoptionsmoduledb.cpp \
           database/historicdb.cpp \
           databasemodule/databasemodule.cpp \
           mainscreen.cpp \
    menusystem/database/databaseconfigwidget.cpp \
    menusystem/design/addinvitationscreenwidget.cpp \
    menusystem/design/deleteinvitationscreenwidget.cpp \
    menusystem/design/deleteofferwidget.cpp \
    menusystem/design/invitationscreendesignwidget.cpp \
    menusystem/design/posdesignselectorwidget.cpp \
    menusystem/design/productscreendesignwidget.cpp \
    menusystem/design/submenuinfoframe.cpp \
    menusystem/menus/genericscreenwidget.cpp \
    menusystem/menus/instantiator.cpp \
    menusystem/menus/mainscreenwidget.cpp \
           menusystem/utils.cpp \
           menusystem/design/shortcutbuttonwidget.cpp \
           menusystem/design/nticketdesignwidget.cpp \
           menusystem/products/productinsertionwidget.cpp \
           menusystem/products/advancedproductinsertionwidget.cpp \
           menusystem/products/advancedproducteditionwidget.cpp \
           menusystem/products/advancedproductdeletionwidget.cpp \
           menusystem/products/advancedproductupdatewidget.cpp \
           menusystem/products/productxmfileupdatewidget.cpp \
           menusystem/products/productoffercreationwidget.cpp \
           menusystem/products/productoptioncreationwidget.cpp \
           menusystem/products/basicproductcreationwidget.cpp \
           menusystem/products/basicproductupdatewidget.cpp \
           menusystem/products/basicproducteditionwidget.cpp \
           menusystem/offers_options/offereditionwidget.cpp \
           menusystem/offers_options/offercreationwidget.cpp \
           menusystem/offers_options/offerupdatewidget.cpp \
           menusystem/offers_options/offerdeletionwidget.cpp \
           menusystem/offers_options/optioneditionwidget.cpp \
           menusystem/offers_options/optioncreationwidget.cpp \
           menusystem/offers_options/optionupdatewidget.cpp \
           menusystem/offers_options/optiondeletionwidget.cpp \
           productsmodule/productmodule.cpp \
           productsmodule/optionsmodule/productoptionmodule.cpp \
           productsmodule/offersmodule/productoffermodule.cpp \
           usersmodule/usermodule.cpp \
           main.cpp \
           menusystem/menus/supportwidget.cpp \
           menusystem/menus/techwidget.cpp \
           menusystem/reports/perszwidget.cpp \
           menusystem/reports/persticketwidget.cpp \
           menusystem/reports/nprofitreportwidget.cpp \
#           menusystem/reports/nprodandofferreportwidget.cpp \
#           menusystem/system/fx2000configwidget.cpp \
#           menusystem/system/memstickwidget.cpp \
           menusystem/system/fx2000enrollwidget.cpp \
           menusystem/system/devicesconfigwidget.cpp \
           menusystem/users/usereditionwidget.cpp \
           menusystem/users/usercreatewidget.cpp \
           menusystem/users/userupdatewidget.cpp \
           menusystem/users/userselectwidget.cpp

FORMS += menusystem/reports/profitreportwidgetbase.4ui \
         menusystem/reports/perszwidgetbase.4ui \
         menusystem/reports/prodandofferreportwidgetbase.4ui \
         menusystem/reports/persticketswidgetbase.4ui \
         menusystem/database/ddbbwidgetbase.4ui \
         menusystem/system/fx2000configwidgetbase.4ui \
         menusystem/system/memstickwidgetbase.4ui \
         menusystem/system/fx2000enrollwidgetbase.4ui \
         menusystem/system/devicesconfigwidgetbase.4ui \
    menusystem/design/newscreeninvitationsinterface.4ui \
    menusystem/design/screeninvitationsdesigninterface.4ui \
    menusystem/design/ticketdesigninterface.4ui \
    menusystem/design/shortcutbuttoninterface.4ui \
    menusystem/design/deletescreeninvitationsinterface.4ui \
    menusystem/design/screenproductsdesigninterface.4ui \
    menusystem/design/deleteofferproductinterface.4ui \
    menusystem/design/posdesignselectorinterface.4ui \
    menusystem/menus/supportwidgetbase.4ui \
    menusystem/menus/techwidgetbase.4ui \
    menusystem/products/productinsertionwidgetbase.4ui \
    menusystem/products/advancedproducteditionwidgetbase.4ui \
    menusystem/products/productxmfileupdatewidgetbase.4ui \
    menusystem/products/productoffercreationwidgetbase.4ui \
    menusystem/products/productoptioncreationwidgetbase.4ui \
    menusystem/products/basicproductcreationwidgetbase.4ui \
    menusystem/products/basicproducteditionwidgetbase.4ui \
    menusystem/offers_options/offereditionwidgetbase.4ui \
    menusystem/offers_options/offerdeletionwidgetbase.4ui \
    menusystem/offers_options/optioneditionwidgetbase.4ui \
    menusystem/users/usercreatewidgetbase.4ui \
    menusystem/users/userselectwidgetbase.4ui

DISTFILES += etc/dtds/products_familieslist.dtd \
             etc/dtds/products_optionslist.dtd \
             etc/dtds/user_example.xml \
             etc/dtds/company_ticket.dtd \
             etc/dtds/users_userslist.dtd \
             etc/dtds/products_taxeslist.dtd \
             etc/dtds/products_productslist.dtd \
             etc/dtds/products_composition.dtd \
             etc/dtds/dcopfx2000_enroll.dtd \
             etc/dtds/dbmodule_config.dtd \
             etc/dtds/products_offerslist.dtd \
             etc/dtds/users_user.dtd \
             etc/devices_description.xml \
             etc/find_databases \
             etc/find_servers \
             etc/database_server.xml \
             etc/mainscreen_description.xml \
             icons/apps/raw/toptitle.xcf \
             icons/apps/raw/downtitle.xcf \
             icons/apps/32x32/edit.png \
             icons/apps/32x32/usb_devices.png \
             icons/apps/32x32/date.png \
             icons/apps/32x32/package.png \
             icons/apps/32x32/ddbb_copy1.png \
             icons/apps/32x32/down.png \
             icons/apps/32x32/galeon.png \
             icons/apps/32x32/ddbb_general.png \
             icons/apps/32x32/viewmag+.png \
             icons/apps/32x32/2rightarrow.png \
             icons/apps/32x32/viewmag-.png \
             icons/apps/32x32/xcalc.png \
             icons/apps/32x32/ddbb_start.png \
             icons/apps/32x32/location_data_user.png \
             icons/apps/32x32/report.png \
             icons/apps/32x32/run.png \
             icons/apps/32x32/ddbb.png \
             icons/apps/32x32/finish.png \
             icons/apps/32x32/2downarrow.png \
             icons/apps/32x32/filenew.png \
             icons/apps/32x32/filesave.png \
             icons/apps/32x32/2leftarrow.png \
             icons/apps/32x32/previous.png \
             icons/apps/32x32/button_semi_ok.png \
             icons/apps/32x32/ksplash.png \
             icons/apps/32x32/2uparrow.png \
             icons/apps/32x32/package_editors.png \
             icons/apps/32x32/kspread.png \
             icons/apps/32x32/forward.png \
             icons/apps/32x32/package_network.png \
             icons/apps/32x32/today.png \
             icons/apps/32x32/stick_32x32.png \
             icons/apps/32x32/button_ok.png \
             icons/apps/32x32/clock.png \
             icons/apps/32x32/ddbb_repair.png \
             icons/apps/32x32/reload.png \
             icons/apps/32x32/ddbb_copy.png \
             icons/apps/32x32/viewmag.png \
             icons/apps/32x32/up.png \
             icons/apps/32x32/back.png \
             icons/apps/32x32/edittrash.png \
             icons/apps/32x32/next.png \
             icons/apps/32x32/personal.png \
             icons/apps/32x32/start.png \
             icons/apps/32x32/serial_devices.png \
             icons/apps/32x32/kpresenter.png \
             icons/apps/32x32/info.png \
             icons/apps/32x32/printer2.png \
             icons/apps/32x32/stop.png \
             icons/apps/32x32/ddbb_shrink.png \
             icons/apps/32x32/editdelete.png \
             icons/apps/32x32/ktip.png \
             icons/apps/32x32/ddbb_stop.png \
             icons/apps/32x32/basic_data_user.png \
             icons/apps/32x32/button_cancel.png \
             icons/apps/32x32/kmessedwords.png \
             icons/apps/32x32/contents.png \
             icons/apps/32x32/cancel.png \
             icons/apps/48x48/network.png \
             icons/apps/48x48/video.png \
             icons/apps/48x48/lounge.png \
             icons/apps/48x48/back_green.png \
             icons/apps/48x48/producto.png \
             icons/apps/48x48/up_green.png \
             icons/apps/48x48/trash.png \
             icons/apps/48x48/recycled.png \
             icons/apps/48x48/z.png \
             icons/apps/48x48/atm_noselection.png \
             icons/apps/48x48/ddbb_copy1.png \
             icons/apps/48x48/down.png \
             icons/apps/48x48/galeon.png \
             icons/apps/48x48/ddbb_general.png \
             icons/apps/48x48/logo_napsis_48.png \
             icons/apps/48x48/fileshare.png \
             icons/apps/48x48/button_ok_48.png \
             icons/apps/48x48/forward_green.png \
             icons/apps/48x48/report.png \
             icons/apps/48x48/run.png \
             icons/apps/48x48/man.png \
             icons/apps/48x48/kpercentage.png \
             icons/apps/48x48/test.png \
             icons/apps/48x48/design1.png \
             icons/apps/48x48/design2.png \
             icons/apps/48x48/design3.png \
             icons/apps/48x48/kcmpci.png \
             icons/apps/48x48/locale.png \
             icons/apps/48x48/users_del.png \
             icons/apps/48x48/ksplash.png \
             icons/apps/48x48/looknfeel.png \
             icons/apps/48x48/ticket.png \
             icons/apps/48x48/home.png \
             icons/apps/48x48/printer.png \
             icons/apps/48x48/hwinfo.png \
             icons/apps/48x48/forward.png \
             icons/apps/48x48/cdtrack.png \
             icons/apps/48x48/design.png \
             icons/apps/48x48/modificar_productos.png \
             icons/apps/48x48/laptop_pcmcia.png \
             icons/apps/48x48/screen1.png \
             icons/apps/48x48/ddbb_repair.png \
             icons/apps/48x48/reload.png \
             icons/apps/48x48/fx2000.jpg \
             icons/apps/48x48/edit_footer.png \
             icons/apps/48x48/ddbb_copy.png \
             icons/apps/48x48/play_prev.png \
             icons/apps/48x48/hdd_unmount.png \
             icons/apps/48x48/play_next.png \
             icons/apps/48x48/users_del1.png \
             icons/apps/48x48/stick_48x48.png \
             icons/apps/48x48/kcmdevices.png \
             icons/apps/48x48/prev.png \
             icons/apps/48x48/borrar_producto.png \
             icons/apps/48x48/edit_header.png \
             icons/apps/48x48/up.png \
             icons/apps/48x48/back.png \
             icons/apps/48x48/next.png \
             icons/apps/48x48/personal.png \
             icons/apps/48x48/general.png \
             icons/apps/48x48/edit_body.png \
             icons/apps/48x48/users_modify.png \
             icons/apps/48x48/kcmsystem.png \
             icons/apps/48x48/info.png \
             icons/apps/48x48/atm.png \
             icons/apps/48x48/product_rewritexml.png \
             icons/apps/48x48/screen1_noselection.png \
             icons/apps/48x48/printer_noselection.png \
             icons/apps/48x48/users.png \
             icons/apps/48x48/mime_html.png \
             icons/apps/48x48/ddbb_shrink.png \
             icons/apps/48x48/info1.png \
             icons/apps/48x48/exit.png \
             icons/apps/48x48/button_cancel.png \
             icons/apps/48x48/screen.png \
             icons/apps/48x48/users_add.png \
             icons/apps/48x48/productos.png \
             icons/apps/48x48/down_green.png \
             icons/apps/48x48/cancel.png \
             icons/apps/64x64/lounge.png \
             icons/apps/64x64/inventory1.png \
             icons/apps/64x64/package.png \
             icons/apps/64x64/package_utilities.png \
             icons/apps/64x64/reports.png \
             icons/apps/64x64/inventory.png \
             icons/apps/64x64/support.png \
             icons/apps/64x64/exit1.png \
             icons/apps/64x64/package_settings.png \
             icons/apps/64x64/logo_napsis_64.png \
             icons/apps/64x64/historico.png \
             icons/apps/64x64/password.png \
             icons/apps/64x64/run.png \
             icons/apps/64x64/ddbb.png \
             icons/apps/64x64/stick_64x64.png \
             icons/apps/64x64/ksplash.png \
             icons/apps/64x64/looknfeel.png \
             icons/apps/64x64/printer.png \
             icons/apps/64x64/package_network.png \
             icons/apps/64x64/design.png \
             icons/apps/64x64/kthememgr.png \
             icons/apps/64x64/tv.png \
             icons/apps/64x64/kfm_home.png \
             icons/apps/64x64/news.png \
             icons/apps/64x64/personal.png \
             icons/apps/64x64/printer1.png \
             icons/apps/64x64/printer2.png \
             icons/apps/64x64/printer4.png \
             icons/apps/64x64/users.png \
             icons/apps/64x64/ktip.png \
             icons/apps/64x64/exit.png \
             icons/apps/64x64/productos.png \
             icons/apps/64x64/sysconf.png \
             icons/apps/64x64/penguin.png \
             icons/apps/toptitle.png \
             icons/apps/hands/r-hand0.png \
             icons/apps/hands/r-hand1.png \
             icons/apps/hands/r-hand2.png \
             icons/apps/hands/r-hand3.png \
             icons/apps/hands/r-hand4.png \
             icons/apps/hands/r-hand.png \
             icons/apps/hands/l-hand.png \
             icons/apps/hands/l-hand0.png \
             icons/apps/hands/l-hand1.png \
             icons/apps/hands/l-hand2.png \
             icons/apps/hands/l-hand3.png \
             icons/apps/hands/l-hand4.png \
             icons/apps/hands/l-hand5.png \
             icons/apps/tile_blur.png \
             icons/apps/ntpv_backoffice_splash.png \
             icons/apps/ntpv_backoffice_splash.xcf \
             icons/apps/ntpv_foot.png \
             icons/apps/ntpv_foot.xcf \
             icons/apps/fx2000.jpg \
             icons/apps/ntpv_header.png \
             icons/apps/ntpv_header.xcf \
             icons/apps/tile.png \
             custom.pri \
             AUTHORS \
             COPYING \
             README \
             TODO \
             postinst
