######################################################################
# Automatically generated by qmake (1.04a) Fri Feb 21 19:06:45 2003
######################################################################

QT += network xml

TEMPLATE = app
INCLUDEPATH += . \
                ..\
                ../..

LIBS += ../../libqutexr.so

HEADERS += validationserver.h
SOURCES += validationserver.cpp main.cpp

