name: cmake

on:
  push:
  pull_request:
  schedule:
    - cron: '0 1 * * SUN'
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        include:
          - CC: gcc-13
            CXX: g++-13
            PackageDeps: g++-13
            Qt: qt.qt6.680.gcc_64
            os: ubuntu-24.04
          - CC: clang-18
            CXX: clang++-18
            PackageDeps: clang-18
            Qt: qt.qt6.680.gcc_64
            Repo: llvm-toolchain-$(lsb_release -cs)-18
            os: ubuntu-24.04
    runs-on: ${{ matrix.os }}
    name: ${{ matrix.os }} ${{ matrix.CXX }}
    env:
      WPOS_SRC: ${{ github.workspace }}/wpos
      WPOS_BUILD: ${{ github.workspace }}/../build
      CC: ${{ matrix.CC }}
      CXX: ${{ matrix.CXX }}
    steps:
    - name: checkout wpos
      uses: actions/checkout@v4
    - name: Add Repo
      run: |
        wget -O - https://apt.llvm.org/llvm-snapshot.gpg.key|sudo apt-key add -
        sudo apt-add-repository "deb http://apt.llvm.org/$(lsb_release -cs)/ ${{ matrix.Repo }} main"
      if: matrix.Repo != ''
    - name: Install Packages Dependencies
      run: |
        sudo apt --yes update
        sudo apt --yes install libxkbcommon-x11-0 ninja-build cmake libcups2-dev libjpeg-dev libpng-dev zlib1g-dev libcrypt-dev libgdchart-gd2-xpm-dev libgd-dev libsqlite3-dev libodb-sqlite-dev libodb-boost-dev libboost1.83-dev libodb-pgsql-dev libodb-qt-dev libodb-dev libxml2-dev odb ${{ matrix.PackageDeps }}
        sudo apt install --yes libfontconfig1-dev libfreetype-dev libx11-dev libx11-xcb-dev libxcb-cursor-dev libxcb-glx0-dev libxcb-icccm4-dev libxcb-image0-dev libxcb-keysyms1-dev libxcb-randr0-dev libxcb-render-util0-dev libxcb-shape0-dev libxcb-shm0-dev libxcb-sync-dev libxcb-util-dev libxcb-xfixes0-dev libxcb-xinerama0-dev libxcb-xkb-dev libxcb1-dev libxext-dev libxfixes-dev libxi-dev libxkbcommon-dev libxkbcommon-x11-dev libxrender-dev
        sudo wget https://d13lb3tujbc8s0.cloudfront.net/onlineinstallers/qt-online-installer-linux-x64-4.8.1.run -O /usr/bin/qt-online-installer 
        sudo chmod u+x /usr/bin/qt-online-installer
        sudo mkdir -pv /root/.local/share/Qt
        sudo cp -a  ${{ github.workspace }}/qtaccount.ini /root/.local/share/Qt/qtaccount.ini
        sudo mkdir -pv /opt/qt
        sudo qt-online-installer --root /opt/qt --accept-licenses --accept-obligations --default-answer --confirm-command install ${{ matrix.Qt }}
      if: matrix.PackageDeps != ''
    - name: Build wPOS 
      run: |
        mkdir -pv ${env:WPOS_BUILD}
        mkdir -pv ${env:WPOS_SRC}/../bin
        mkdir -pv ${env:WPOS_SRC}/../lib
        cmake -DCMAKE_PREFIX_PATH:PATH=/opt/qt/gcc_64 -S ${env:WPOS_SRC} -B ${env:WPOS_BUILD} -G Ninja
        cmake --build ${env:WPOS_BUILD} --target all --parallel
      shell: pwsh
