name: Linux with Qt Deb Packages

on:
  push:
  pull_request:
  schedule:
    - cron: '0 1 * * SUN'
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        include:
          - CC: gcc-13
            CXX: g++-13
            PackageDeps: g++-13
            os: ubuntu-24.04
          - CC: clang-18
            CXX: clang++-18
            PackageDeps: clang-18
            Repo: llvm-toolchain-$(lsb_release -cs)-18
            os: ubuntu-24.04
    runs-on: ${{ matrix.os }}
    name: ${{ matrix.os }} ${{ matrix.CXX }}
    env:
      WPOS_SRC: ${{ github.workspace }}/wpos
      WPOS_BUILD: ${{ github.workspace }}/../build
      CC: ${{ matrix.CC }}
      CXX: ${{ matrix.CXX }}
    steps:
    - name: checkout wpos
      uses: actions/checkout@v4
    - name: Add Repository ${{ matrix.Repo }}
      run: |
        wget -O - https://apt.llvm.org/llvm-snapshot.gpg.key|sudo apt-key add -
        sudo apt-add-repository "deb http://apt.llvm.org/$(lsb_release -cs)/ ${{ matrix.Repo }} main"
      if: matrix.Repo != ''
    - name: Install Packages Dependencies
      run: |
        sudo apt update --yes && sudo apt upgrade --yes 
        sudo apt install --yes ubuntu-release-upgrader-core && sudo do-release-upgrade --quiet --mode=desktop
        sudo apt install --yes qt6-pdf-dev qt6-websockets-dev qt6-webengine-dev qt6-5compat-dev qt6-base-dev qt6-base-dev-tools ninja-build cmake libxml2-dev libcups2-dev libjpeg-dev libpng-dev zlib1g-dev libcrypt-dev libgdchart-gd2-xpm-dev libgd-dev odb libodb-dev libsqlite3-dev libodb-sqlite-dev libodb-pgsql-dev libodb-mysql-dev libboost1.83-dev libodb-boost-dev libodb-qt-dev ${{ matrix.PackageDeps }}
      if: matrix.PackageDeps != ''
    - name: Run Configure wPOS 
      run: |
        mkdir -pv ${env:WPOS_BUILD}
        mkdir -pv ${env:WPOS_SRC}/../bin
        mkdir -pv ${env:WPOS_SRC}/../lib
        cmake -S ${env:WPOS_SRC} -B ${env:WPOS_BUILD} -G Ninja
      shell: pwsh
    - name: Build wPOS 
      run: |
        cmake --build ${env:WPOS_BUILD} --target all --parallel
      shell: pwsh
