name: Linux with Qt Online Installer

on:
  push:
  pull_request:
  schedule:
    - cron: '0 1 * * SUN'
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        include:
          - QtRepo: qt6.8.1-essentials extensions.qtpdf.681.linux_gcc_64 extensions.qtwebengine.681.linux_gcc_64 qt.qt6.681.addons.qtpositioning qt.qt6.681.addons.qtwebsockets qt.qt6.681.addons.qtwebchannel                  qt.qt6.681.addons.qtwebview qt.qt6.681.addons.qt5compat qt.tools  
          - CC: gcc-13
            CXX: g++-13
            PackageDeps: g++-13
            #Qt: qt6.8.1-essentials extensions.qtpdf.681.linux_gcc_64 extensions.qtwebengine.681.linux_gcc_64 qt.qt6.681.addons.qtpositioning qt.qt6.681.addons.qtwebsockets qt.qt6.681.addons.qtwebchannel qt.qt6.681.addons.qtwebview qt.qt6.681.addons.qt5compat qt.tools
            os: ubuntu-24.04
          - CC: clang-18
            CXX: clang++-18
            PackageDeps: clang-18
            #Qt: qt6.8.1-essentials qt6.8.1-addons qt.qt6.681.addons.qt5compat extensions.qtpdf.681 extensions.qtwebengine.681 extensions.qtinsighttracker.681 qt.tools
            Repo: llvm-toolchain-$(lsb_release -cs)-18
            os: ubuntu-24.04
    runs-on: ${{ matrix.os }}
    name: ${{ matrix.os }} ${{ matrix.CXX }}
    env:
      WPOS_SRC: ${{ github.workspace }}/wpos
      WPOS_BUILD: ${{ github.workspace }}/../build
      CC: ${{ matrix.CC }}
      CXX: ${{ matrix.CXX }}
    steps:
    - name: Checkout wPOS
      uses: actions/checkout@v4
    - name: Add Repository ${{ matrix.Repo }}
      run: |
        wget -O - https://apt.llvm.org/llvm-snapshot.gpg.key|sudo apt-key add -
        sudo apt-add-repository "deb http://apt.llvm.org/$(lsb_release -cs)/ ${{ matrix.Repo }} main"
      if: matrix.Repo != ''
    - name: Install Packages Dependencies
      run: |
        sudo apt update --yes
        sudo apt install --yes libglvnd-dev libxkbcommon-x11-dev libfontconfig1-dev libfreetype-dev libx11-dev libx11-xcb-dev libxcb-cursor-dev libxcb-glx0-dev libxcb-icccm4-dev libxcb-image0-dev libxcb-keysyms1-dev libxcb-randr0-dev libxcb-render-util0-dev libxcb-shape0-dev libxcb-shm0-dev libxcb-sync-dev libxcb-util-dev libxcb-xfixes0-dev libxcb-xinerama0-dev libxcb-xkb-dev libxcb1-dev libxext-dev libxfixes-dev libxi-dev libxrender-dev ninja-build cmake libxml2-dev libcups2-dev libjpeg-dev libpng-dev zlib1g-dev libcrypt-dev libgdchart-gd2-xpm-dev libgd-dev odb libodb-dev libsqlite3-dev libodb-sqlite-dev libodb-pgsql-dev libodb-mysql-dev libboost1.83-dev libodb-boost-dev libodb-qt-dev ${{ matrix.PackageDeps }}
        sudo wget --quiet https://d13lb3tujbc8s0.cloudfront.net/onlineinstallers/qt-online-installer-linux-x64-4.8.1.run -O /usr/bin/qt-online-installer 
        sudo chmod u+x /usr/bin/qt-online-installer
        sudo mkdir -pv /root/.local/share/Qt
        sudo cp -a  ${{ github.workspace }}/qtaccount.ini /root/.local/share/Qt/qtaccount.ini
        sudo mkdir -pv /opt/qt
        sudo qt-online-installer --no-default-installations --no-force-installations --root /opt/qt --accept-licenses --accept-obligations --default-answer --confirm-command install ${{ matrix.QtRepo }}
      if: matrix.PackageDeps != ''
    - name: Configure wPOS 
      run: |
        mkdir -pv ${env:WPOS_BUILD}
        mkdir -pv ${env:WPOS_SRC}/../bin
        mkdir -pv ${env:WPOS_SRC}/../lib
        cmake -DCMAKE_PREFIX_PATH:PATH=/opt/qt/6.8.1/gcc_64 -S ${env:WPOS_SRC} -B ${env:WPOS_BUILD} -G Ninja
      shell: pwsh
    - name: Build wPOS 
      run: |
        cmake --build ${env:WPOS_BUILD} --target all --parallel
      shell: pwsh
